### ISSUE TITLE
knapsack_pro depends on knapsack

### ISSUE THREAD

**Issue by m5rk** [KnapsackPro/knapsack_pro-ruby#117]
So why not specify that in the .gemspec? That way, I can simply add `gem 'knapsack_pro` to my Gemfile instead of both?

**Comment by ArturT** [comment]
Hi @m5rk 

knapsack_pro gem does not depend on knapsack gem. You can remove knapsack gem from your Gemfile and please follow the installation guide to configure knapsack_pro gem https://docs.knapsackpro.com/knapsack_pro-ruby/guide/ :)
