### ISSUE TITLE
Can Knapsack_Pro read rspec tests from a file? (a question, not an issue)

### ISSUE THREAD

**Issue by Neal910** [KnapsackPro/knapsack_pro-ruby#128]
### What I am doing:
I integrated [Crystalball project](https://github.com/toptal/crystalball) with Knapsack_Pro. Here is how they work:  Crystalball output the list of tests that needs to be ran because they are connected to the ruby code that have been changed by developers, so we only run selected portion of rspec tests. Now Knapsack_Pro need to take this list into `KNAPSACK_PRO_TEST_FILE_LIST` to start running them in parallel.

The code to run it is something like below:
```
        KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true \
        KNAPSACK_PRO_PROJECT_DIR=. \
        KNAPSACK_PRO_CI_NODE_TOTAL=$CI_NODE_TOTAL \
        KNAPSACK_PRO_CI_NODE_INDEX=$(($CI_NODE_INDEX-1)) \
        KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC=<the token> \
        KNAPSACK_PRO_TEST_FILE_LIST=$(cat tmp/crystalball_prediction) \
        bundle exec rake "knapsack_pro:queue:rspec[--format documentation --format RspecJunitFormatter --out tmp/rspec.xml]"
```
NOTE: the `crystalball_prediction` file is the output of Crystalball project.

However I am facing an issue that the number of tests in this file is sometimes too large, so I got argument list too large issue like this: ```/usr/local/bin/bundle: Argument list too long```. I believe the tests being `cat` out is too large then it is over the `ARG_MAX` of the nodes. However I didn't get luck to increase the stack to make it work.

Therefor I am wondering if there is a way to ask knapsack_pro read test cases from a file? so I don't have to print it into the parameter. Thanks.

**Comment by Neal910** [comment]
I know we could do something like this https://knapsackpro.com/faq/question/how-to-run-tests-from-a-specific-directory-only-system-tests-or-features-specs but I really need to run specific tests to eliminate any un-necessary time spending.

**Comment by ArturT** [comment]
Hi @Neal910 

I'm wondering how we could do it.

Maybe we could introduce a new env var `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE`

Then you could set env var `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE=tmp/crystalball_prediction.txt` in your CI.

The knapsack_pro could do read the file, something like `File.read(ENV['KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE'])`. 

We could assume each new line in `tmp/crystalball_prediction.txt` has single test file path.


Here we could add a `test_file_list_source_file` method definition to read from  `KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE`  env var: https://github.com/KnapsackPro/knapsack_pro-ruby/blob/b05db5d2d87db595ab0c3ca6fa73e809080bd7f0/lib/knapsack_pro/config/env.rb#L74

and then here we would need to add a new if statement similar to this one
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/b05db5d2d87db595ab0c3ca6fa73e809080bd7f0/lib/knapsack_pro/test_file_finder.rb#L62

it could look like this:

```ruby
if test_file_list_enabled && KnapsackPro::Config::Env.test_file_list_source_file
  # example return value should be array of test files. We would need to read files from file File.read(KnapsackPro::Config::Env.test_file_list_source_file) and split line one by one to get array of test files
   return ['spec/a_spec.rb', 'spec/b_spec.rb']
end
```

@Neal910 Would you be able to help prepare a pull request and test if this would work for your project?
I could take over from there once you test this solution is working for you.

**Comment by Neal910** [comment]
That looks awesome. It should be exactly what I want. Much appreciated.

**Comment by Neal910** [comment]
I have made the changes on my local, can you allow me to push my branch? @ArturT Thanks.

**Comment by ArturT** [comment]
@Neal910 Can you fork this repo and push your branch to your copy of the repo and then create pull request. This way I could merge your code changes to my repo.

https://opensource.com/article/19/7/create-pull-request-github

**Comment by Neal910** [comment]
Thanks. Here you go ^^^

**Comment by ArturT** [comment]
I've merged your [PR](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/129) and released a new version of knapsack_pro gem. Please update it. Thanks for your help with this feature.
