### ISSUE TITLE
Queue mode seems to have malformed JUnit formatting

### ISSUE THREAD

**Issue by tmtrademarked** [KnapsackPro/knapsack_pro-ruby#134]
We're running our tests using knapsack-pro's queue mode functionality - and it seems to be mangling the output JUnit format files. Here's an example (elided) of what we see in our junit format at the end of a run:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="1561" skipped="0" failures="0" errors="0" time="11.379601" timestamp="2020-11-24T22:52:53+00:00" hostname="57c67ee37a85">
<properties>
<property name="seed" value="64613"/>
</properties>
<testcase classname="spec.controllers.api.devise.sessions_controller_spec" name="Api::Devise::SessionsController DELETE #destroy when unauthenticated user should return 401" file="./spec/controllers/api/devise/sessions_controller_spec.rb" time="0.034123"></testcase>
...
</testsuite>
.services.order_fulfillment_service_spec" name="OrderFulfillmentService.request_order_fulfillment with existing created fulfillment request created recently behaves like does not create a fulfillment request does not create a new one" file="./spec/services/order_fulfillment_service_spec.rb" time="0.331101"></testcase>
...
</testsuite>
```

Notice that one of the lines is not fully formed - it appears that KnapsackPro is attempting to merge the results of multiple files or some such, but doesn't seem to be doing it successfully.

We are using knapsack-pro 2.8.0, and running the following command:
```
bundle exec rake "knapsack_pro:queue:rspec[--tag ~unit --tag ~flake --colour --format Fuubar --format RspecJunitFormatter --out test_reports/junit-report-integration-${TEST_NODE_INDEX}.xml]"
```

We've even tried setting `export KNAPSACK_PRO_MODIFY_DEFAULT_RSPEC_FORMATTERS=false` in our build scripts prior to running the `rake`, but to no avail. Any idea what's happening here?

**Comment by ArturT** [comment]
Hi @tmtrademarked 

Please apply this config as suggested for Queue Mode:
https://knapsackpro.com/faq/question/how-to-use-junit-formatter

**Comment by ArturT** [comment]
BTW I see you use `--tag ~unit` to exclude test files. 
It is recommended to filter out test files by knapsack_pro instead of leaving it to RSpec for performance reasons. 

https://knapsackpro.com/faq/question/how-to-exclude-tests-from-running-them

Other useful tips on how to define list of test files to be run with knapsack_pro gem:
https://knapsackpro.com/faq/question/how-to-run-tests-from-a-specific-directory-only-system-tests-or-features-specs
https://knapsackpro.com/faq/question/how-can-i-run-tests-from-multiple-directories

**Comment by tmtrademarked** [comment]
Thanks! I just found that documentation, and will give it a try.
