### ISSUE TITLE
Feature requests(adding --seed & --bisect to rspec debug command)

### ISSUE THREAD

**Issue by partounian** [KnapsackPro/knapsack_pro-ruby#156]
Could you please add the `--seed #{seed_number}` and `--bisect` so we don't have to manually add these flags to debug the CI?

**Comment by ArturT** [comment]
Hi @partounian 

Basically, you would like the seed number to be automatically added to the below message:

```
I, [2021-08-06T22:43:53.827804 #47352]  INFO -- : [knapsack_pro] To retry in development the subset of tests fetched from API queue please run below command on your machine. If you use --order random then remember to add proper --seed 123 that you will find at the end of rspec command.
I, [2021-08-06T22:43:53.827920 #47352]  INFO -- : [knapsack_pro] bundle exec rspec --format d  --default-path spec "spec/controllers/dashboard/pending_controller_spec.rb"
```

We would need to figure out how to extract the seed number from RSpec.
I'm not sure if RSpec provides a way for that. 
[This should be a good starting point](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/32f566f6863784d3e1d615ff06f8400645d786b5/lib/knapsack_pro/runners/queue/rspec_runner.rb#L110) if you would like to help with this.

I'm wondering should we always add the bisect option? Maybe not every user wants to use it?
Docs for bisect. 
https://relishapp.com/rspec/rspec-core/docs/command-line/bisect

**Comment by shadre** [comment]
> 

@partounian displaying of the relevant `--seed` option has been added in the [3.4.1 version](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#341).

**Comment by ArturT** [comment]
I was wondering, maybe adding the `--bisect` option should be a user decision, not the `knapsack_pro` gem doing it by default. I can imagine someone wants to just retry tests without the bisect option.

@partounian Is adding `--bisect` option still something you find useful and needed? Or it's not needed, and we could close this issue for now.

**Comment by partounian** [comment]
Hey,

Sadly I haven't been using Ruby since my last job so I don't have a need for this.
