### ISSUE TITLE
Ci failing with missing file error

### ISSUE THREAD

**Issue by tachyons** [KnapsackPro/knapsack_pro-ruby#166]
I am experimenting with knapsack pro for a project with circleci. My tests are randomly failing with this error. am i missing some configurations ?

`Errno::ENOENT: No such file or directory @ rb_sysopen - .knapsack_pro/tracker/prerun_tests_RSpecAdapter_node_1.json`

**Comment by ArturT** [comment]
This looks similar to the error from another user https://github.com/KnapsackPro/knapsack_pro-ruby/pull/165

Most likely you have a typo in the bind method called in spec helper:

Please add at the beginning of your `spec/rails_helper.rb` or `spec/spec_helper.rb`:

```ruby
require 'knapsack_pro'
KnapsackPro::Adapters::RSpecAdapter.bind
```

This is from the installation guide: https://docs.knapsackpro.com/knapsack_pro-ruby/guide/

Please ensure the name of RSpec has 2 capital letters `RS` in the `RSpecAdapter` name.

Let me know if this helps.

**Comment by tachyons** [comment]
That is unlikely to be the case as I have written the correct name
![Uploading Screenshot 2022-01-19 at 6.36.44 AM.png…]()

**Comment by ArturT** [comment]
By any chance do you see errors about no permission access while writing to the directory `.knapsack_pro`?

knapsack_pro gem creates the `.knapsack_pro` directory for temporary files inside of your project directory. 

I'm wondering if your issue could be related to this https://github.com/KnapsackPro/knapsack_pro-ruby/issues/158

Could you share all errors you see (full backtrace). If you don't want to share it publicly please send an email to the support https://knapsackpro.com/contact 
 I could also check what's recorded on our API side for your account by knowing your email address.

**Comment by ArturT** [comment]
This issue has been solved. The root cause of the issue was that `Dir.pwd` was getting reset in one spec which caused the knapsack_pro gem process to not find the `.knapsack` directory as knapsack_pro uses a relative path to fetch config. `Dir.chdir` with a block in the user's codebase is not thread-safe by design.
