### ISSUE TITLE
Ability to set an exit code for RSpec failure

### ISSUE THREAD

**Issue by geoffharcourt** [KnapsackPro/knapsack_pro-ruby#169]
Hi,

We'd like to fail with a particular exit code when RSpec is unsuccessful. I tried putting the argument in our Rake command with `rake "knapsack_pro:rspec[--failure-exit-code=3]"
` but it didn't seem to take. Is there a way to pass that argument on to RSpec? 

This is useful for CI providers because we want to retry for infrastructure failures but not for spec failures, and we can control this by using a custom exit code.

**Comment by ArturT** [comment]
Hi @geoffharcourt 

I see you use Knapsack Pro in Regular Mode. In the Regular Mode, we invoke the RSpec rake task. I'm not sure why it does not respect the `--failure-exit-code=3` option. 
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/50f969646c8cb92333f70715604bebb8852e72f3/lib/knapsack_pro/runners/rspec_runner.rb#L34

Maybe you could create a bash script `bin/knapsack_pro_run_tests` and override the exit code:

```bash
#!/bin/bash

# run tests in parallel with Knapsack Pro Regular Mode for RSpec
bundle exec rake knapsack_pro:rspec
export KNAPSACK_PRO_EXIT_CODE=$?

# process should exit with non zero exit code when one of test failed
if [ "$KNAPSACK_PRO_EXIT_CODE" -ne "1" ]; then
  exit 3
fi
```

**Comment by geoffharcourt** [comment]
Hi @ArturT your code is the workaround we're currently using, I was just wondering if there was a more straightforward way!

BTW, we normally run in queue mode in CI, I just had that command shortened for the test I was running locally. (Assuming that doesn't make a difference.)

Thanks for your help!

**Comment by ArturT** [comment]
In the Queue Mode the non-zero exit code from the RSpec is remembered for each batch of tests fetched from Knapsack Pro API Queue.

A non-zero exit code should be returned in the Queue Mode:
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/50f969646c8cb92333f70715604bebb8852e72f3/lib/knapsack_pro/runners/queue/rspec_runner.rb#L89

I've just manually tested the Queue Mode and the `--failure-exit-code=3` option. When my test case is failing then knapsack_pro gem returns `3` as the exit code

```
bundle exec rake "knapsack_pro:queue:rspec[--format d --failure-exit-code 3]"
...some output from running test
echo $? # run this to preview the exit code
3
```

Maybe knapsack_pro is not the last command in your CI pipeline and that is why your CI does not see `3` as exit code?

**Comment by geoffharcourt** [comment]
Interesting! We will investigate! Thanks for your help.
