### ISSUE TITLE
Knapsack not running all the cuke scenarios on the nodes assigned

### ISSUE THREAD

**Issue by rajkokkula** [KnapsackPro/knapsack_pro-ruby#17]
Hi Arthur,

We have been using travis with Knapsack Pro and I see that lately it is not running all the scenarios on the nodes assigned. Besides I see that sometimes its running the duplicate scenarios.  Can you please let me know if there has been any change to the gem or do we need to upgrade our knapsack pro gem version.

Regards
Rajani

**Comment by ArturT** [comment]
Did you try version knapsack_pro 0.10.0. I fixed there problem with sometimes duplicated tests in some specific cases. You can read more about it in changelog:
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#0100

and here are a bit more info:
https://github.com/KnapsackPro/knapsack_pro-ruby#knapsack_pro_fixed_test_suite_splite-test-suite-split-based-on-seed

Please let me know if that helps.

**Comment by ArturT** [comment]
@rajkokkula Could you let me know if that solves your problem?
