### ISSUE TITLE
rspec_junit_formatter still producing invalid XML after applying suggestion from #40

### ISSUE THREAD

**Issue by cccCody** [KnapsackPro/knapsack_pro-ruby#171]
I'm working on enabling queue mode and splitting tests by examples for my project, and I ran into what looks like the same problem in issue https://github.com/KnapsackPro/knapsack_pro-ruby/issues/40. At first, I had invalid XML from every node, with cutoff text outside of XML tags. I found [this article](
https://knapsackpro.com/faq/question/how-to-use-junit-formatter#how-to-use-junit-formatter-with-knapsack_pro-queue-mode) and tried applying the suggestion, but I still see invalid XML on 2 out of 26 CI nodes. Looking at the XML, I see duplicate `<?xml version="1.0" encoding="UTF-8"?>` declarations halfway through the file, and no closing `</xml>`.

My build script calls the following rake task:
```
rake "knapsack_pro:queue:rspec[--format documentation --format RspecJunitFormatter --out tmp/junit/rspec.xml --failure-exit-code 0]"
```

spec_helper.rb has this:
```
TMP_RSPEC_XML_REPORT = 'tmp/junit/rspec.xml'.freeze
FINAL_RSPEC_XML_REPORT = "tmp/junit/node_#{ENV.fetch('KNAPSACK_PRO_CI_NODE_INDEX')}-rspec_final_results.xml".freeze

KnapsackPro::Hooks::Queue.after_subset_queue do
  if File.exist?(TMP_RSPEC_XML_REPORT)
    FileUtils.mv(TMP_RSPEC_XML_REPORT, FINAL_RSPEC_XML_REPORT)
  end
end
```

**Comment by shadre** [comment]
Is the XML invalid for exactly 2 nodes always? Do they happen to have the same node index every time?

**Comment by cccCody** [comment]
It does seem to be fairly consistently failing on 2 nodes, but they're not the same nodes. In fact, our nodes are EC2 instances that we spin up on-demand and use only once, so it's not like there's some difference across nodes that would explain why it would fail on some but not others. Maybe those happen to be the 2 nodes that have their set of tests changed during the course of the build? Just an idea...

**Comment by cccCody** [comment]
Following up from our email thread, this was the result of specs exercising code that calls `Kernel#exit`, which has some unexpected (to me at least) behavior in rspec:
https://github.com/rspec/rspec-core/issues/2246#issuecomment-221784644
