### ISSUE TITLE
Docs need to specify ENV var to detect CI provider

### ISSUE THREAD

**Issue by tomchipchase** [KnapsackPro/knapsack_pro-ruby#204]
I've just had to add `BUILDKITE` to the list of environment variables passed down to docker for running CI after upgrading to 5.1.0.

It looks like this is necessary after this change https://github.com/KnapsackPro/knapsack_pro-ruby/pull/201, but the docs don't specify `BUILDKITE` as one of the variables we need to pass down.

![image](https://github.com/KnapsackPro/knapsack_pro-ruby/assets/621252/d2caceff-e1fe-4c6d-9088-9bcdb8c99bbc)

**Comment by ArturT** [comment]
@tomchipchase Thanks for reporting this. I updated the docs.
