### ISSUE TITLE
Fail gracefully when there's no git

### ISSUE THREAD

**Issue by ngan** [KnapsackPro/knapsack_pro-ruby#210]
We're seeing this in our log after upgrading to 5.2.0:

<img width="1058" alt="image" src="https://github.com/KnapsackPro/knapsack_pro-ruby/assets/16579/1efb7d97-bcf8-499d-a770-cab07cf82396">

Our codebase doesn't have git during running specs. Is there a way for us to give this information to knapsack? Maybe env variable?

**Comment by ArturT** [comment]
Thanks for reporting this. I'll raise this with our team.

Is this stopping you from running tests?

We expected the command to fail quietly in case there is no git on the CI.

**Comment by ArturT** [comment]
@ngan Is clone of the repository inside of the CI at different location? 
@3v0k4 If so we could provide a location of the repo with `-C` like we did here:

https://github.com/KnapsackPro/knapsack_pro-ruby/blob/e1b301de28e4a6afb6e655a054977409013cc316/lib/knapsack_pro/repository_adapters/git_adapter.rb#L56
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/e1b301de28e4a6afb6e655a054977409013cc316/lib/knapsack_pro/repository_adapters/git_adapter.rb#L5

The error looks like git is installed on the CI but is not executed inside of the repository.

**Comment by ngan** [comment]
We tar up our code to distribute across hundreds of agents. We exclude the .git directory purposefully to reduce space and time to download.

**Comment by 3v0k4** [comment]
Thanks for the report @ngan.

It looks like `git` prints to stderr but the tests are run properly, correct?

**Comment by ngan** [comment]
Yup

**Comment by ngan** [comment]
It’s not urgent. It just doesn’t look good.

**Comment by 3v0k4** [comment]
@ngan please `bundle update knapsack_pro` to >=5.3.1 and let me know if it fixes the problem.
