### ISSUE TITLE
Does `rake knapsack_pro:rspec_test_example_detector` need to run if there aren't any slow specs?

### ISSUE THREAD

**Issue by technicalpickles** [KnapsackPro/knapsack_pro-ruby#223]
While doing some local testing, I have sometimes seen the log output from this line:

https://github.com/KnapsackPro/knapsack_pro-ruby/blob/4d9dc1436470995773aa080d8054f6c587aef91b/lib/knapsack_pro/base_allocator_builder.rb#L46

Does the rake task still need to run if  `slow_test_files.size == 0`? It is relatively fast (15s locally), but if there aren't any slow specs, it'd be nice to save a little time.

**Comment by ArturT** [comment]
I guess it could be skipped, then. We'll have to check that.

**Comment by ArturT** [comment]
@technicalpickles This is solved in the knapsack_pro gem [5.7.0 version](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#570). Please update the knapsack_pro gem in your project.
