### ISSUE TITLE
Slow test analysis runs even when there's no slow tests

### ISSUE THREAD

**Issue by ngan** [KnapsackPro/knapsack_pro-ruby#224]
We don't always build every single test but it looks like the slow test analysis always runs even when there's no slow test:
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/lib/knapsack_pro/base_allocator_builder.rb#L55

No slow tests being that [`slow_test_files = get_slow_test_files`](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/lib/knapsack_pro/base_allocator_builder.rb#L44C17-L44C17) is an empty array.

An optimization to make would be to see if we actually got any slow tests back from the `get_slow_test_files` call. If we got an empty array, it should just bypass the [analysis](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/lib/knapsack_pro/base_allocator_builder.rb#L46-L61) completely.

**Comment by shadre** [comment]
Thanks for the suggestion.

We are aware of that and plan to address this. I'm closing this as it's a dup of: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/223.

**Comment by ArturT** [comment]
@ngan This is solved in the knapsack_pro gem [5.7.0 version](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#570). Please update the knapsack_pro gem in your project.
