### ISSUE TITLE
Disable example_status_persistence_file_path

### ISSUE THREAD

**Issue by technicalpickles** [KnapsackPro/knapsack_pro-ruby#227]
Mentioned this on https://github.com/KnapsackPro/knapsack_pro-ruby/pull/226#issuecomment-1771179449

> I did find another benefit to doing this. If you have config.example_status_persistence_file_path set, you end up loading and dumping the status for all specs each time.
>
> We ended up disabling this during CI. I could see it being a knapsack pro default if there is a good place to set it. 

[Documentation about this feature](https://rubydoc.info/gems/rspec-core/RSpec%2FCore%2FConfiguration:example_status_persistence_file_path):

>The file path to use for persisting example statuses. Necessary for the --only-failures and --next-failure CLI options.

I came across this while investigating https://github.com/KnapsackPro/knapsack_pro-ruby/issues/200 , and I saw a lot of memory allocations from the code that generates and publishes this file. Since knapsack wouldn't be using `--on-failures` or `--next-failure`, it should be safe to disable these.

**Comment by ArturT** [comment]
What do you mean by disabling `example_status_persistence_file_path`? Is it about getting rid of some internal RSpec code that is responsible for handling that?

If a user does not set `example_status_persistence_file_path` in their `spec_helper.rb`, does it mean RSpec is still consuming a lot of memory?

We have some customers using `--only-failures` option to retry flaky tests. This is [documented here](https://docs.knapsackpro.com/ruby/rspec/#retry-failedflaky-tests).
This means they need to set `example_status_persistence_file_path`.

**Comment by ArturT** [comment]
Ok. So no action for now.


By default `config.example_status_persistence_file_path` is not used by the majority of users so they have no memory consumption issue.

Some customers use `config.example_status_persistence_file_path` and they use RSpec in Queue Mode and this can cause increased memory consumption. This is the issue you discovered.

When we merge PR https://github.com/KnapsackPro/knapsack_pro-ruby/pull/226 then the issue won't exist anymore for the customers. So let's focus on the PR.

I'm closing this one for now.
