### ISSUE TITLE
NoMethodError: undefined method `rspec_is_quitting'

### ISSUE THREAD

**Issue by whizzzkid** [KnapsackPro/knapsack_pro-ruby#238]
knapsack_pro seems to fail with rspec 3.10, the minimum version that supports this method is 3.11, Can this be explicitly be called out in the documentation?

**Comment by ArturT** [comment]
Thanks for reporting this. 

I have a fix for that in #237 so that we could support older RSpec versions.

Is this issue blocking you? Can you update the RSpec version in your project?

**Comment by ArturT** [comment]
I realized we already fixed that issue in the knapsack_pro 6.0.1 version.

* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/231

Changelog: https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#601

Please update the knapsack_pro gem to the latest version.
