### ISSUE TITLE
Failing RSpec tests on ~>7.0.0

### ISSUE THREAD

**Issue by AnkeshThakur** [KnapsackPro/knapsack_pro-ruby#246]
I am setting up Knapsack Pro with gem version 7.0.0 and 7.0.1. Tests are failing with both the versions which otherwise is passing. 

I am mostly getting two types of error which relates to `instance_double` tests and materialize-view dependent tests. Following is the error description from the runs

```Failures:

  1) SalesforceAppConfiguration AASM when revoked when activate with active subscription with stored auth transitions
     Failure/Error:
       allow(app_configuration).to receive(:salesforce_authentication)
                                     .and_return(instance_double(Salesforce::Authentication,
                                                                 refresh_token: 'aBc'))

       the Salesforce::Authentication class does not implement the instance method: refresh_token
     # ./spec/models/salesforce_app_configuration_spec.rb:121:in `block (7 levels) in <top (required)>'
     # ./spec/spec_helper.rb:209:in `block (2 levels) in <main>'

  2) SalesforceAppConfiguration AASM when new when activate with active subscription with stored auth transitions
     Failure/Error:
       allow(app_configuration).to receive(:salesforce_authentication)
                                     .and_return(instance_double(Salesforce::Authentication,
                                                                 refresh_token: 'aBc'))

       the Salesforce::Authentication class does not implement the instance method: refresh_token
     # ./spec/models/salesforce_app_configuration_spec.rb:63:in `block (7 levels) in <top (required)>'
     # ./spec/spec_helper.rb:209:in `block (2 levels) in <main>'
.
.
.
Finished in 3 minutes 19.4 seconds (files took 1.04 seconds to load)
888 examples, 10 failures, 1 pending
```

Other error:

``` ActiveRecord::StatementInvalid:
       PG::ObjectNotInPrerequisiteState: ERROR:  materialized view "best_product_medals" has not been populated
       HINT:  Use the REFRESH MATERIALIZED VIEW command.
     # ./app/domain/medals/list.rb:47:in `map'
     # ./app/domain/medals/list.rb:47:in `wrap_medals'
     # ./app/domain/medals/list.rb:21:in `block in medals'
     # ./app/domain/medals/list.rb:21:in `each'
     # ./app/domain/medals/list.rb:21:in `flat_map'
     # ./app/domain/medals/list.rb:21:in `medals'
     # ./app/domain/vendor_admin/medals/product_medals.rb:15:in `medal_class_and_ids'
     # ./app/domain/vendor_admin/medals/product_medals.rb:9:in `exclude?'
     # ./app/models/product_reference_page_medal.rb:54:in `medal_invalid?'
     # ./spec/models/product_reference_page_medal_spec.rb:24:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:207:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::ObjectNotInPrerequisiteState:
     #   ERROR:  materialized view "best_product_medals" has not been populated
     #   HINT:  Use the REFRESH MATERIALIZED VIEW command.
     #   ./app/domain/medals/list.rb:47:in `map'
```

I am trying to set it up on Github Actions with VCR/WebMosck setup. All of these tests are passing when I try it with 6.0.4. 

Following is the command that I'm using to invoke the test in GHA runner `bundle exec rake "knapsack_pro:queue:rspec[--require packs/rails/rspec --require spec_helper --order rand --require fivemat --format Fivemat --format RSpec::Github::Formatter --format RspecJunitFormatter --out report/ruby-rspec-${{ matrix.node_index }}.xml]"`

**Comment by ArturT** [comment]
Could you prepare an integration test like [this one](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/45d7c135eb92f13fe8eea7260825c644e5111ddb/spec/integration/runners/queue/rspec_runner_spec.rb#L382) to help us reproduce an issue?

Or it could be a new Rails app that we could use to debug it? 

Thank you.

**Comment by GeoffTidey** [comment]
Hi @ArturT do you mean something like https://github.com/KnapsackPro/knapsack_pro-ruby/pull/247/files ?

**Comment by ArturT** [comment]
@GeoffTidey Yes.

I've run this test and it's passing successful.

```
➜  knapsack_pro-ruby git:(pr/247) rspec spec/integration/runners/queue/rspec_runner_spec.rb:382
Resolving dependencies...
Run options: include {:locations=>{"./spec/integration/runners/queue/rspec_runner_spec.rb"=>[382]}}

Randomized with seed 65516

KnapsackPro::Runners::Queue::RSpecRunner - Integration tests
  when rails_helper file exists
    requires the rails_helper file when running RSpec and runs hooks defined within it

Finished in 0.2351 seconds (files took 0.42629 seconds to load)
1 example, 0 failures

Randomized with seed 65516
```

We need to prepare a test that would fail with the same error as you see in your project. Then we could prepare a fix for that.

Are you able to identify what is causing the error in your project?

**Comment by GeoffTidey** [comment]
Afraid not.  It's intermittent.

**Comment by GeoffTidey** [comment]
Hi @ArturT , sorry for the radio silence.  It's not been happening at all since my last update.  Two things have changed, the first is probably the issue:

1. I moved the `KnapsackPro::Adapters::RSpecAdapter.bind` to spec/spec_helper.rb (it was perviously in another helper that is only loaded for system tests), 
2. the other is we're now using GitHub Actions for CI, rather than Heroku CI.

**Comment by ArturT** [comment]
@GeoffTidey Thank you for providing solution to your issue. 

@AnkeshThakur Could you ensure `KnapsackPro::Adapters::RSpecAdapter.bind` is in `spec/spec_helper.rb`?

You could also update the knapsack_pro gem to the latest version. We released a couple of improvements.

I'd appreciate an update from you. If it's no longer a relevant issue, please let me know.

**Comment by AnkeshThakur** [comment]
@ArturT apology for silence. I'm no longer integrating KnapsackPro. For me older version (<7.0.0) worked without issue.


I have not updated it to later version to check if 7+ versions are working or not.
