### ISSUE TITLE
Unable to run cucumber - missing requires?

### ISSUE THREAD

**Issue by rosskevin** [KnapsackPro/knapsack_pro-ruby#25]
I'm not sure what or where I'm missing it, but it seems that I cannot run cucumber on circleci as it breaks in the junit formatter.  This doesn't occur locally with the same Gemfile.lock running `bundle exec cucumber`.

The undefined object is the `step` itself.

Any thoughts?

```bash
bundle exec rake "knapsack_pro:cucumber"
I, [2017-02-20T17:07:38.408884 #23231]  INFO -- : [knapsack_pro] API request UUID: 
I, [2017-02-20T17:07:38.409048 #23231]  INFO -- : [knapsack_pro] API response:
I, [2017-02-20T17:07:38.409147 #23231]  INFO -- : [knapsack_pro] {"build_distribution_id"=>nil, "node_index"=>0, "test_files"=>[{"path"=>"features/public_pages.feature", "time_execution"=>nil}]}
/opt/circleci/ruby/ruby-2.3.1/bin/ruby -S bundle exec cucumber --require features -- features/public_pages.feature
I, [2017-02-20T17:07:44.631094 #23727]  INFO -- : [knapsack_pro] Test suite time execution recording enabled.
Using the default profile...

undefined method `name' for nil:NilClass (NoMethodError)
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:114:in `hook?'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:105:in `create_output_string'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/junit.rb:62:in `on_after_test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `block in notify'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `each'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/events/bus.rb:27:in `notify'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/event_bus_report.rb:28:in `after_test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/bin/cucumber:23:in `load'
/home/ubuntu/af/vendor/bundle/ruby/2.3.0/bin/cucumber:23:in `<top (required)>'
```

**Comment by ArturT** [comment]
Hey @rosskevin 

I did test for knapsack_pro cucumber command with junit formatter on CircleCI. 
Could you confirm you have junit formatter configured the same way as here?

```yaml
# circle.yml
test:
  override:
    - bundle exec rake "knapsack_pro:cucumber[--format junit --out tmp/cucumber_junit.xml]":
        parallel: true
```

Here is example build that passed:
https://circleci.com/gh/KnapsackPro/rails-app-with-knapsack_pro/382

My circle.yml
https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/master/circle.yml

I also tested it locally and it worked.
I used cucumber 2.4.0 as in your logs.

I checked the source code of cucumber and found the line that fails:
https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/junit.rb#L116

Maybe you could `binding.pry` there in your environment or ssh to CircleCI and try to debug it:

It seems @failing_step_source is nil.
`hook?` is called here https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/junit.rb#L107

Maybe some of your gem's dependencies are not up to date for cucumber? Or this problem is somehow related to your test suite or some problem in one of your test?

**Comment by rosskevin** [comment]
I have tried all three of these with the same results. 

```
    - bundle exec rake "knapsack_pro:cucumber[--format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber]":

    - bundle exec rake "knapsack_pro:cucumber":

    - bundle exec rake "knapsack_pro:cucumber[--format junit --out $CIRCLE_TEST_REPORTS/cucumber/junit.xml]":
```

 It must be an app failure of a feature or an unexpected condition (like a failure in a background).  Strange that it works on OSX.   Thanks for taking a look.  I'll update this when I figure it out.

**Comment by rosskevin** [comment]
This may have to do with some recent changes with rails 5, but most certainly seems to be a problem with my engine/dummy app setup.  Still investigating and am able to reproduce locally.

**Comment by ArturT** [comment]
@rosskevin Ok. Please let me know if you will find out something. I will prepare example app for rails5 with various test runners to ensure knapsack_pro works with it.

**Comment by rosskevin** [comment]
Seems like a requires problem for a rails engine.

```
engine
-> app (engine code)
-> features
-> spec
      -> dummy
            -> app (sample app location)          
```

We run the app from `spec/dummy`, but manipulate the scripts to run from the engine root.  I'm going back to default scripts to see if I can get it to work.

**Comment by ArturT** [comment]
You can provide path to your tests to `KNAPSACK_PRO_TEST_FILE_PATTERN` env variable.

This is default for cucumber: `KNAPSACK_PRO_TEST_FILE_PATTERN="features/**{,/*/**}/*.feature"`. Maybe this will help you somehow.

**Comment by rosskevin** [comment]
Thanks, I have reset my cucumber configs to the default and it is running features without errors.

**Comment by devkid** [comment]
@ArturT I'm having the exact same problem. I used pry to debug a bit. The error occurs when an exception is thrown in a scenario hook (`Around` hook for me). In this case, `on_after_test_step` is never called and `@failing_step_source` is never set (or `event.test_step.source.last` is `nil`). So this seems to be bug.

**Comment by ArturT** [comment]
Hi @devkid 
I'd love to help you but I'm not able to reproduce it with limited info. Could you send me private message at my email https://knapsackpro.com/contact so you won't post here private data about your project.

Please let me know what email you used to signed up on https://knapsackpro.com so I will be able to check server logs.
And could you share your output with error and if it is related to specific test file could you share how the test looks like. What is your gems versions? Do you use cucumber specific gems?

**Comment by ArturT** [comment]
@devkid I tried to reproduce it by raising an exception in the test but without success.
Please contact me so we could figure out what's the root problem in your case.
