### ISSUE TITLE
Ruby 3.3 support?

### ISSUE THREAD

**Issue by mikebaldry** [KnapsackPro/knapsack_pro-ruby#255]
I tried running our test suite against Ruby 3.3.1 today and the tests just never finished on multiple workers. They were just sitting there doing nothing and I killed the build after an hour.

I initially thought this was something Ruby related, but after removing Knapsack from our CI scripts, everything works.

**Comment by mikebaldry** [comment]
I'm running through these steps now, I'll email over to you with my findings. 

Thanks

**Comment by ArturT** [comment]
Summary after private conversation.

Disabling YJIT helps.

The issue might be related to YJIT: 
* https://github.com/ruby/ruby/pull/10787

**Comment by ArturT** [comment]
I'm closing this issue because disabling YJIT helped.

@mikebaldry I've replied in our private conversation. Please let me know if you need more help.

**Comment by J-Swift** [comment]
Hello from the future. We might be seeing something similar. Our GH actions runners are 'hanging' and ultimately timing out. What was previously a consistent 3m45s test run is now never finishing.

We recently updated to ruby 3.3, but we've had YJIT enabled for a long while. Any additional insight you might have gotten between now and your last update?

**Comment by ArturT** [comment]
Hi @J-Swift 

A hanging node problem on GitHub Actions was reported to us yesterday by another customer. It was related to GitHub Actions degradation: https://www.githubstatus.com/history.
You might have experienced the same issue.

In addition, I recommend using the latest knapsack_pro gem. It includes features to help you debug when tests are hanging.
You can follow this guide to narrow down whether any code or resources are causing the process to hang:
https://docs.knapsackpro.com/ruby/troubleshooting/#why-does-the-ci-node-hang-backtrace-debugging

**Comment by ArturT** [comment]
@J-Swift Please share the text output from the hanging CI node with support at:
https://knapsackpro.com/contact,
and I can review it afterward.

**Comment by ArturT** [comment]
@jpcamara Could you please check if any of the following suggestions help?
https://docs.knapsackpro.com/ruby/troubleshooting/#knapsack-pro-hangs

Could you also double-check if there is enough memory available on the CI?

If none of the above helps, please use the following guide to get the backtrace from the hanging CI node. It should point to the line of code that is causing the issue:
https://docs.knapsackpro.com/ruby/troubleshooting/#why-does-the-ci-node-hang-backtrace-debugging
Please share the backtrace with me via support@knapsackpro.com.

Thank you.
