### ISSUE TITLE
CLI ENV variables not passed by rake task

### ISSUE THREAD

**Issue by rosskevin** [KnapsackPro/knapsack_pro-ruby#26]
When I use something like this for local testing:

```
RAILS_ENV=test CI=true mkdir -p test-reports/cucumber && bundle exec rake "knapsack_pro:cucumber[--format junit --out test-reports/cucumber/junit.xml]" 
```

The `RAILS_ENV` and `CI` variable changes aren't passed through to my running code.  This is only a trivial bug, but it took me some time to figure out that the rake task wasn't allowing these through as you would see when running the equivalent `RAILS_ENV=test CI=true bundle exec rake cucumber`.

**Comment by ArturT** [comment]
Hey @rosskevin, this is normal bash behavior. 
You could write your command like this so the ENV vars will be also visible to rake task.

```
export RAILS_ENV=test; export CI=true; mkdir -p test-reports/cucumber && bundle exec rake "knapsack_pro:cucumber[--format junit --out test-reports/cucumber/junit.xml]" 
```

You can read more about it here:
http://stackoverflow.com/questions/10856129/setting-an-environment-variable-before-a-command-in-bash-not-working-for-second
