### ISSUE TITLE
Improve handling of skipped tests and dynamic parallelism

### ISSUE THREAD

**Issue by devinburnette** [KnapsackPro/knapsack_pro-ruby#261]
Trying to figure out if there's a way that [datadog-ci](https://github.com/DataDog/datadog-ci-rb/) and knapsack can be better integrated, maybe this is just a queue mode problem, but here's the scenario I'm trying to solve for:

[datadog's ITR](https://docs.datadoghq.com/intelligent_test_runner/) examines the test coverage and determines that most of the tests can actually be skipped, but we still pass the full list of tests to knapsack in our CI config. knapsack determines subsets and breaks the list up but because most things are being skipped, some parallel nodes end up with no tests to run and it throws the entire split timings out of wack and the job takes too long to complete (in some cases longer than without skipping any tests).

I'm wondering if there's a way we can either have knapsack be aware of skipped tests when determining subsets and make the distribution better based on that, and/or somehow introduce the idea of dynamic parallelism and just determine the proper number of nodes to be ran based on the number of tests that will actually run effectively fixing the split timings issue.

/cc @ArturT @anmarchenko

**Comment by anmarchenko** [comment]
From Datadog side, I would be happy to provide a list of skipped tests to knapsack library at some point in the lifecycle; unfortunately right now we instrument the `knapsack:queue:rspec_go` command that is running after the parallel runners are created. The runners are created outside of knapsack (in static config of Circle CI), so I am curious what could be done in this case.

**Comment by ArturT** [comment]
@devinburnette Please ensure you use the latest version of the knapsack_pro gem and datadog-ci.

>  knapsack determines subsets and breaks the list up but because most things are being skipped, some parallel nodes end up with no tests to run and it throws the entire split timings out of wack and the job takes too long to complete (in some cases longer than without skipping any tests).

Could you share a link to the problematic CI build in the knapsack_pro dashboard or commit hash?

@anmarchenko said:

> The runners are created outside of knapsack (in static config of Circle CI), so I am curious what could be done in this case.

@devinburnette  Does it mean you use CircleCI and the `Rerun only failed tests` feature?
https://docs.knapsackpro.com/ruby/circleci/#rerun-only-failed-tests

Is the problem related to retried CI nodes that run only a subset of the test suite? In such case CircleCI reruns all the nodes but only some would run tests when there is less test files than the number of parallel nodes. Number of parallel nodes would have to be configured in CircleCI yml config file even if Knapsack API could provide the suggested number of parallel nodes to use.

> [datadog's ITR](https://docs.datadoghq.com/intelligent_test_runner/) examines the test coverage and determines that most of the tests can actually be skipped, but we still pass the full list of tests to knapsack in our CI config.

@devinburnette How do you pass list of tests to Knapsack?

**Comment by ArturT** [comment]
@anmarchenko Are tests skipped by DataDog during the runtime of the RSpec tests? Or does DataDog return a list of tests to skip up front and then Knapsack is fed with the list using [KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_test_file_list_source_file)?

**Comment by anmarchenko** [comment]
Individual tests within a test file

**Comment by anmarchenko** [comment]
Yes, Datadog evaluates the idea to provide some script for knapsack's edge case to return percentage of skipped tests (the best we can do on library's side), we will see if this is going to be enough for @devinburnette's case

**Comment by ArturT** [comment]
The percentage of skipped tests might be good enough. If you run only 20% of the test suite, then you could also run 20% of the parallel nodes, or a bit more if these 20% of tests are very slow.

**Comment by ArturT** [comment]
@anmarchenko Please let me know if I can assist with anything, or post an update here if you have made any progress. Thank you.

**Comment by anmarchenko** [comment]
We are testing this idea with @devinburnette, so far not clear if it works:
https://github.com/DataDog/datadog-ci-rb/pull/194

**Comment by devinburnette** [comment]
For anyone following this issue, since https://github.com/KnapsackPro/knapsack_pro-ruby/pull/282 introduced the `KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD` env var. We are just setting this env var in conjunction with `KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true` to something reasonable in seconds like `KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD=180` to make sure any test file with execution time longer than 3 min. will be split by example. This will ensure knapsack maintains a more even split when the parallelism changes between runs and some tests are being skipped.
