### ISSUE TITLE
log threads unable to give the backtrace

### ISSUE THREAD

**Issue by devinburnette** [KnapsackPro/knapsack_pro-ruby#270]
I think there's a bug in the `log_threads` method introduced [here](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/266/files) where it will blow up if the backtrace for a thread is nil for whatever reason.

I got this stacktrace on a test run:
```
NoMethodError: undefined method `join' for nil:NilClass
/home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.7.0/lib/knapsack_pro/runners/queue/base_runner.rb:83:in `block in log_threads': undefined method `join' for nil:NilClass (NoMethodError)
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.7.0/lib/knapsack_pro/runners/queue/base_runner.rb:75:in `each'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.7.0/lib/knapsack_pro/runners/queue/base_runner.rb:75:in `log_threads'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.7.0/lib/knapsack_pro/runners/queue/base_runner.rb:62:in `block (2 levels) in trap_signals'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/type/hash_lookup_type_map.rb:44:in `key?'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/type/hash_lookup_type_map.rb:44:in `key?'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:702:in `get_oid_type'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:60:in `block (2 levels) in exec_query'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:57:in `each'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:57:in `each_with_index'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:57:in `block in exec_query'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:750:in `execute_and_clear'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/querying.rb:54:in `_query_by_sql'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:942:in `block in exec_main_query'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:962:in `skip_query_cache_if_necessary'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:928:in `exec_main_query'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:914:in `block in exec_queries'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:962:in `skip_query_cache_if_necessary'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:908:in `exec_queries'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/association_relation.rb:44:in `exec_queries'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:695:in `load'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:250:in `records'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/relation.rb:245:in `to_ary'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/associations/association.rb:224:in `find_target'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:264:in `load_target'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_proxy.rb:43:in `load_target'
	from /home/betterment/retail/investing/vendor/bundle/ruby/3.2.0/gems/ac
	...
```

Build ID: a525cf31-784f-44f0-baa8-f881e0fa4715

**Comment by ArturT** [comment]
@devinburnette Thanks for reporting this.

Could you work around the issue while we look into it? Or is this preventing you from using Knapsack Pro?

**Comment by devinburnette** [comment]
No it doesn't block usage. From what I can tell, it just prevents us from getting the backtrace to determine why a build is hanging.

**Comment by devinburnette** [comment]
Another data point here, I saw another couple of these today and it looked like these were the result of cancelled builds, so certain trapped signals may not result in backtraces which makes sense.

**Comment by ArturT** [comment]
This makes sense. Thank you for clarifying it.

**Comment by devinburnette** [comment]
more data on this.. I think it's possible that because of this error, RSpec does not catch the signal and therefore other downstream things that rely on RSpec receiving the signal and going into `RSpec.world.wants_to_quit` do not happen.

**Comment by devinburnette** [comment]
Thanks! Just one follow-up question here, by handling the signals in this way, does that impede RSpec from getting the request to quit and perform its own exit hooks?

**Comment by ArturT** [comment]
> ...  does that impede RSpec from getting the request to quit and perform its own exit hooks?

@devinburnette  No, unless your CI provider terminated the machine so quickly that RSpec didn't have time to gracefully exit.

**Comment by anmarchenko** [comment]
@ArturT there could be an issue with your handling of INT signal though.. 

RSpec uses it to set `RSpec.world.wants_to_quit`: 
https://github.com/rspec/rspec-core/blob/c905f8539341418675bea4cf6bb5f66605262292/lib/rspec/core/runner.rb#L175-L192

Knapsack alkso traps the same signal:
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/5ae1d312727d38a30c79b889bdc3f8c6e676679c/lib/knapsack_pro/runners/queue/base_runner.rb#L58-L65

When you use Signal.trap, the signal handler is overridden and then the original handler is returned:
https://github.com/ruby/ruby/blob/0f3dc2f958bd1447cc459bc4a4f39071a6a07a9c/signal.c#L1322-L1347

Knapsack seemingly ignores the return value and doesn't set `RSpec.world.wants_to_quit` to `true` which makes me wonder if RSpec termination will be really graceful in this case

**Comment by ArturT** [comment]
Thanks for sharing this, @anmarchenko 
I think we are good. I don't see anything in [the RSpec source code](https://github.com/search?q=repo%3Arspec%2Frspec-core%20wants_to_quit&type=code) that we missed. For reference, we use our own [RSpec extension (monkey patch)](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/5ae1d312727d38a30c79b889bdc3f8c6e676679c/lib/knapsack_pro/extensions/rspec_extension.rb#L7).

The difference is that when you use knapsack_pro, the INT signal will terminate the process. If you use RSpec, you must receive INT twice. RSpec [prints this message](https://github.com/rspec/rspec-core/blob/c905f8539341418675bea4cf6bb5f66605262292/lib/rspec/core/runner.rb#L175-L192):

```ruby
  $stderr.puts(
            "\nRSpec is shutting down and will print the summary report... Interrupt again to force quit " \
            "(warning: at_exit hooks will be skipped if you force quit)."
          )
```

We don't want to do it.

---

@devinburnette when you mentioned exit hooks, did you mean only [RSpec hooks](https://rspec.info/documentation/3.3/rspec-core/RSpec/Core/Hooks.html) or something else that your rely on? If you notice anything missing or not executed, please let me know. Thank you.

**Comment by anmarchenko** [comment]
@ArturT thanks for your answer!

I think the search results you posted miss this:
https://github.com/rspec/rspec-core/blob/3f10b72cef2da026b6e7392c0b33a217a44a8f41/lib/rspec/core/runner.rb#L184

RSpec sets `RSpec.world.wants_to_quit = true` when receiving SIGINT, that signals everyone that RSpec is going to quit. 

For example, for @devinburnette it is quite important that datadog-ci bails out of retrying tests when RSpec received INT signal:
https://github.com/DataDog/datadog-ci-rb/blob/main/lib/datadog/ci/contrib/rspec/example.rb#L67-L70

There could be other libraries that depend on RSpec's correct state, but knapsack_pro gem prevents RSpec from setting its state, replacing it by knapsack's own `@@terminate_process`, which is this library's implementation detail.

**Comment by ArturT** [comment]
@anmarchenko The knapsack_pro [7.8.2 version](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#782) has been released with a proper fix.

**Comment by anmarchenko** [comment]
@ArturT thanks a lot! 

@devinburnette let me know if you have any more issues with canceled jobs
