### ISSUE TITLE
Node Total greater less than 2 raises

### ISSUE THREAD

**Issue by devinburnette** [KnapsackPro/knapsack_pro-ruby#271]
Hello,

Trying to figure out dynamic parallelism for our CI setup. I noticed that when we take our node parallelism down to just 1 node, we get this error from what appears to be the backend.

```
ArgumentError: {"errors"=>[{"node_total"=>["must be greater than or equal to 2"]}]} (ArgumentError)

        raise ArgumentError.new(response) if connection.errors?
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This unfortunately makes us litter the code with conditionals based on the parallelism, like:

```
if parallelism > 1
  use the knapsack runner
else
  use the rspec runner
end
```

I wonder if it would be better to just fallback to running rspec regularly instead of raising for this specific argument error? Not sure if that would be possible.

**Comment by ArturT** [comment]
Thanks for reporting. I'll bring this up to our team.

**Comment by ArturT** [comment]
We have made a change on the API side. You can now run Knapsack Pro with a single CI node.

@devinburnette Please confirm if this works for you.

**Comment by devinburnette** [comment]
I guess that's one way to do it! Appears to work fine. I guess where my head goes next is.. Is there a way to make onboarding an app more seamless?

Like if we wanted to get rid of the conditional and just use knapsack everywhere that used to require updating the parallelism to something greater than 1, and this is now fixed. But it also requires us to go provision a token for every app we have, and then remember to provision a token for a new app.

Any recommended solutions for making that go away since we can't just fall back to using regular rspec?

**Comment by devinburnette** [comment]
Also, doing it this way actually adds unnecessary time to the execution. Not terrible, but still.

Execution time without parallelization: 40 seconds
Execution time with Knapsack Pro: 47 seconds

**Comment by devinburnette** [comment]
Like maybe somewhere:

```ruby
if test_suite_token_rspec.blank?
  KnapsackPro.logger.warn("Not Running with Knapsack because token not set")
  KnapsackPro::Config::Env.set_test_runner_adapter(original_rspec)
end

if ci_node_total < 2
  KnapsackPro.logger.warn("Not Running with Knapsack because no parallel CI nodes")
  KnapsackPro::Config::Env.set_test_runner_adapter(original_rspec)
end
```

**Comment by ArturT** [comment]
> Also, doing it this way actually adds unnecessary time to the execution. Not terrible, but still.
> 
> Execution time without parallelization: 40 seconds Execution time with Knapsack Pro: 47 seconds

If you use 1 node then you could use Regular Mode. It would fetch tests in a single batch so it could be faster.

```
bundle exec rake knapsack_pro:rspec
```

**Comment by devinburnette** [comment]
> If you use 1 node then you could use Regular Mode. It would fetch tests in a single batch so it could be faster.

Yes, I could, but again I would need to implement that conditional logic myself.. I think what i'm proposing is that knapsack could become smarter by making the right choice for me based on various factors.

**Comment by ArturT** [comment]
> I guess that's one way to do it! Appears to work fine. I guess where my head goes next is.. Is there a way to make onboarding an app more seamless?
> 
> Like if we wanted to get rid of the conditional and just use knapsack everywhere that used to require updating the parallelism to something greater than 1, and this is now fixed. But it also requires us to go provision a token for every app we have, and then remember to provision a token for a new app.
> 
> Any recommended solutions for making that go away since we can't just fall back to using regular rspec?

You could use a single API token and add the name of the project to the branch name ([`KNAPSACK_PRO_BRANCH`](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_branch)). I've seen this working for one of our users.

```
export KNAPSACK_PRO_BRANCH="my-project-name/$CIRCLE_BRANCH"
```

**Comment by devinburnette** [comment]
this is what we're already doing, I'm proposing baking that logic into knapsack, so that we don't have to do that, and makes onboarding apps a little easier.

**Comment by devinburnette** [comment]
> You could use a single API token and add the name of the project to the branch name ([KNAPSACK_PRO_BRANCH](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_branch)). I've seen this working for one of our users.

this might work, will give it a try
