### ISSUE TITLE
Trying knapsack, but not able to pass arguments to rspec

### ISSUE THREAD

**Issue by aponsin** [KnapsackPro/knapsack_pro-ruby#3]
This is how I have rspec builds configured on semaphore `bundle exec rspec --tag ~ci_skip -f p spec` but I am not able to pass the arguments to knapsack: 

```
bundle exec rake knapsack_pro:rspec[--tag ~ci_skip -f p]
rake aborted!
No Rakefile found (looking for: p])

(See full trace by running task with --trace)

```

**Comment by aponsin** [comment]
Nevermind, I am stupid.

**Comment by ArturT** [comment]
In case anyone will find this issue, you missed quote marks.
```
 bundle exec rake "knapsack_pro:rspec[--tag focus]"
```
https://github.com/KnapsackPro/knapsack_pro-ruby#passing-arguments-to-rake-task
