### ISSUE TITLE
Documentation: Codeship advice for unique builds requires a new API key

### ISSUE THREAD

**Issue by geoffharcourt** [KnapsackPro/knapsack_pro-ruby#61]
Hi,

I followed the instructions to set `KNAPSACK_PRO_CI_NODE_BUILD_ID=""` in my Codeship environment, but it causes the test suite to never start. (I would get an `ArgumentError` about a missing `node_build_id`).

I changed settings several times in an attempt to determine what was going on, and found that I could only start tests successfully with this setting if I had a brand new SHA or I rotated my Knapsack API key. It might be worth mentioning in the README when giving this instruction to advise users to try the builds with a new key.

**Comment by ArturT** [comment]
Good catch! You can set `KNAPSACK_PRO_CI_NODE_BUILD_ID=missing-build-id` or generate unique ID before each CI build.

I've updated the docs:
https://github.com/KnapsackPro/knapsack_pro-ruby#why-when-i-reran-the-same-build-same-commit-hash-etc-on-codeship-then-no-tests-would-get-executed-in-queue-mode

Let me know if that looks better.

**Comment by geoffharcourt** [comment]
Thank you, @ArturT! This is a fantastic product, it's been a total game-changer for us.
