### ISSUE TITLE
timing resets on feature branches

### ISSUE THREAD

**Issue by bgentry** [KnapsackPro/knapsack_pro-ruby#8]
Hi, I've been running Knapsack Pro on Buildkite for a few days now. I just noticed that a feature branch I created directly off our latest `master` branch seems to have forgotten all about timing info when its specs ran.

Each of the 20 parallel builds showed timing values of `nil` for every single file they're running:

```
** Invoke knapsack_pro:rspec (first_time)
** Execute knapsack_pro:rspec
I, [2016-05-10T22:20:04.894834 #52]  INFO -- : [knapsack_pro] API request UUID: 293b1b17-9d09-4798-b1ed-11196faa48e0
I, [2016-05-10T22:20:04.894932 #52]  INFO -- : [knapsack_pro] API response:
I, [2016-05-10T22:20:04.895297 #52]  INFO -- : [knapsack_pro] {"node_index"=>3, "test_files"=>[{"path"=>"spec/features/happy_path_spec.rb", "time_execution"=>nil}, {"path"=>"spec/models/addresses_response_spec.rb", "time_execution"=>nil}, ...truncated...]}
I, [2016-05-10T22:20:05.478307 #57]  INFO -- : [knapsack_pro] Test suite time execution recording enabled.
```

Is this supposed to happen? I would have expected Knapsack to start with the timing from the latest master build rather than resetting every time. If this is how it's supposed to behave, I don't think it will be very useful to us.

**Comment by ArturT** [comment]
@bgentry Thanks for reporting this. I did fix and now it will use data from master branch.

**Comment by bgentry** [comment]
@ArturT thanks! looks like it's working already 👏 🎉
