### ISSUE TITLE
Disable banner and disable knapsack locally

### ISSUE THREAD

**Issue by leehambley** [KnapsackPro/knapsack_pro-ruby#82]
I'm in a team who uses knapsack, and locally we always get a banner telling us about knapsack pro, etc.

We have an (ancient) knapsack pro report committed else knapsack blows up with errors about that file not being a file ENOENT.

Is there a way to keep knapsack loaded but disable it? (I searched for env vars that might do the trick, and found none, and not much in the way of doce)

Or is the preferred solution to avoid loading knapsack all together in environments where it's not used?

**Comment by ArturT** [comment]
Hi Lee,

here is repo of [knapsack free gem](https://github.com/ArturT/knapsack) and there is [readme](https://docs.knapsackpro.com/ruby/knapsack)

You control when to load knapsack gem in Gemfile like:

```ruby
group :test, :development do
  gem 'knapsack'
end
```

Also `Rakefile` and `spec_helper.rb` loads knapsack. If you need more control over it you can just do in Gemfile:

```ruby
gem 'knapsack', require: false
```

and then `require 'knapsack'` wherever you need to load it.


The json report file is only for knapsack free gem. The knapsack_pro store reports on Knapsack Pro API side so you can access it in user dashboard https://knapsackpro.com/

What CI do you use? I have a few articles showing how Pro version helps with tests distribution thanks to dynamic tests allocation in Queue Mode https://docs.knapsackpro.com/

Here is explanation how Queue Mode works https://www.youtube.com/watch?v=hUEB1XDKEFY 

If you could provide more info about your project context and what do you want to achieve I could better help. Do you use RSpec or something else? How long it takes to run your tests? How many parallel CI nodes do you have?
