### ISSUE TITLE
Readme syntax

### ISSUE THREAD

**Issue by spencersteiner** [KnapsackPro/knapsack_pro-ruby#93]
Under the section that briefly mentions "linters" it uses the `$CI_NODE_TOTAL` variable, where I believe it's supposed to be the index `$CI_NODE_INDEX` variable provided by Heroku CI.

Happy to open a PR if that's easier to review!

**Comment by ArturT** [comment]
I believe you meant this part:

```
KNAPSACK_PRO_CI_NODE_TOTAL=$((CI_NODE_TOTAL-1)) bundle exec rake knapsack_pro:rspec
```
in https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-run-knapsack_pro-only-on-a-few-parallel-ci-nodes-instead-of-all

It's on purpose `CI_NODE_TOTAL` there.  

This example shows case when you want to run tests on N-1 nodes only to have available last parallel node to run other non test related task there like linters :)

**Comment by spencersteiner** [comment]
@ArturT Oh sorry, I was actually meaning this snippet in the first part of the if statement: 

```
# 15 is last CI node (index starts from 0, so in total we have 16 parallel Heroku dynos)
if [ "$CI_NODE_TOTAL" == "15" ]; then
  # run npm tests on the last CI node
  npm test
else
  KNAPSACK_PRO_CI_NODE_TOTAL=$((CI_NODE_TOTAL-1)) bundle exec rake knapsack_pro:queue:rspec
fi
```

Where it says `if [ "$CI_NODE_TOTAL" == "15" ]; then` shouldn't that be when the _index_ is 15 (last node), execute npm test? If it's based on the total then it would never run in this example, because the total is 16 correct? (meaning `$CI_NODE_TOTAL` would never be equal to "15" in this case)

**Comment by ArturT** [comment]
@spencersteiner Oh, that's true. I missed that. Thanks so much, very good catch :)
I fixed that https://github.com/KnapsackPro/knapsack_pro-ruby/commit/21b428c741266d60290c4aaf1463ade026ab7864

**Comment by spencersteiner** [comment]
@ArturT Awesome, no problem :) Thanks for the quick response!
